inherit_gem:
  rubocop-govuk:
    - config/default.yml
    - config/rails.yml
    - config/rspec.yml

inherit_mode:
  merge:
    - Exclude

# **************************************************************
# TRY NOT TO ADD OVERRIDES IN THIS FILE
#
# This repo is configured to follow the RuboCop GOV.UK styleguide.
# Any rules you override here will cause this repo to diverge from
# the way we write code in all other GOV.UK repos.
#
# See https://github.com/alphagov/rubocop-govuk/blob/main/CONTRIBUTING.md
# **************************************************************

# rubocop-rspec was not enabled on this project for most of its life. We autocorrected most
# violations, but the following common rule violations can't be autocorrected and should be fixed
# manually eventually:
RSpec/ContextWording:
  Enabled: false
RSpec/InstanceVariable:
  Enabled: false
RSpec/NamedSubject:
  Enabled: false
RSpec/NoExpectationExample: # Some specs use methods to set up expectations
  Enabled: false
RSpec/VerifiedDoubles:
  Enabled: false
